/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _INTERFACESERVIDORMODULOSERVIDORDISPLAY_H_RPCGEN
#define _INTERFACESERVIDORMODULOSERVIDORDISPLAY_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXIDENTIFICACION2 20

struct moduloActualizado {
	int turno;
	int noModulo;
	bool_t ocupado;
	char identificacionUsuario[MAXIDENTIFICACION2];
};
typedef struct moduloActualizado moduloActualizado;

struct notificacion {
	moduloActualizado modulos[3];
	int cantidadUsuariosFilaVirtual;
};
typedef struct notificacion notificacion;

#define notificar_modulos 0x20000002
#define notificar_modulos_version 1

#if defined(__STDC__) || defined(__cplusplus)
#define enviarNotificacion 1
extern  void * enviarnotificacion_1(notificacion *, CLIENT *);
extern  void * enviarnotificacion_1_svc(notificacion *, struct svc_req *);
extern int notificar_modulos_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define enviarNotificacion 1
extern  void * enviarnotificacion_1();
extern  void * enviarnotificacion_1_svc();
extern int notificar_modulos_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_moduloActualizado (XDR *, moduloActualizado*);
extern  bool_t xdr_notificacion (XDR *, notificacion*);

#else /* K&R C */
extern bool_t xdr_moduloActualizado ();
extern bool_t xdr_notificacion ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_INTERFACESERVIDORMODULOSERVIDORDISPLAY_H_RPCGEN */
