/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "InterfaceServidorModuloServidorDisplay.h"
#include <stdio.h>
#include <stdbool.h>
#include <time.h>

void mostrarHoraUltimaActualizacion(){
	time_t tiempo_actual;
	struct tm *info_tiempo; 

	time(&tiempo_actual);

	info_tiempo = localtime(&tiempo_actual);

	printf("\n Ultima actualizacion: %02d:%02d\n",
		info_tiempo->tm_hour,
		info_tiempo->tm_min); 
	
}

void *
enviarnotificacion_1_svc(notificacion *argp, struct svc_req *rqstp)
{
	static char * result;

	printf("\n		Modulos dispobles ");
	printf("\n Turno Modulo Cliente");
	for(int i=0; i<3;i++){
		if((*argp).modulos[i].ocupado ==true){
			printf("\n %d		%d 		%s",(*argp).modulos[i].turno,(*argp).modulos[i].noModulo,(*argp).modulos[i].identificacionUsuario);
		}
	}
	printf("\n Cantidad de usuarios en la fila virtual: %d", (*argp).cantidadUsuariosFilaVirtual);
	mostrarHoraUltimaActualizacion(); 
	printf("\n");
	return (void *) &result;
}
