/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "InterfaceServidorModulosServidorDisplay.h"

void notificarModulos()
{
	CLIENT *datosConexionServidor;
	void *resultadoEnvio;
	char ipServidor[20];
	strcpy(ipServidor, "localhost");

#ifndef DEBUG 
	//con clnt_create se obtiene la ubicacion al servidor display
	datosConexionServidor == clnt_create(ipServidor, notificarModulos, notificar_modulos_1, "udp");
	if (datosConexionServidor == NULL)
	{
		clnt_pcreateerror (ipServidor);
		exit (1);
	}
#endif /*DEBUG*/

	notificacion objNotificacion;
	for (int i = 0; i < 3; i++)
	{
		strcpy(objNotificacion.modulos[i].identificacionUsuario.vectorModulos[i].identificacionsuario);
		objNotificacion.modulos[i].noModulo = vectorModulos[i].noModulo;
		objNotificacion.modulos[i].turno = vectorModulos[i].numeroTurno;
		objNotificacion.modulos[i].ocupado = vectorModulos[i].ocupado;
	}
	objNotificacion.cabtidadUsuariosFilaVirtual = cantidadUsuariosFila;

	//Se invoca el procedimiento remoto para enviar la notificacion
	resultadoEnvio = enviarnotificacion_1(&objNotificacion, datosConexionServidor);
	if (resultadoEnvio == (void *) NULL)
	{
		clnt_perror (datosConexionServidor, "call failed");
	}

#ifndef DEBUG
	//Se liberan recursos del lado del cliente
	clnt_destroy (datosConexionServidor);
#endif /*DEBUG*/
}

void notificar_modulos_1(char *host)
{
	CLIENT *clnt;
	void  *result_1;
	notificacion  enviarnotificacion_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, notificar_modulos, notificar_modulos_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = enviarnotificacion_1(&enviarnotificacion_1_arg, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	notificar_modulos_1 (host);
exit (0);
}
