/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "InterfaceServidorModuloServidorDisplay.h"

bool_t
xdr_moduloActualizado (XDR *xdrs, moduloActualizado *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->turno))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->noModulo))
				 return FALSE;
			 if (!xdr_bool (xdrs, &objp->ocupado))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->turno);
		IXDR_PUT_LONG(buf, objp->noModulo);
		IXDR_PUT_BOOL(buf, objp->ocupado);
		}
		 if (!xdr_vector (xdrs, (char *)objp->identificacionUsuario, MAXIDENTIFICACION2,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->turno))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->noModulo))
				 return FALSE;
			 if (!xdr_bool (xdrs, &objp->ocupado))
				 return FALSE;

		} else {
		objp->turno = IXDR_GET_LONG(buf);
		objp->noModulo = IXDR_GET_LONG(buf);
		objp->ocupado = IXDR_GET_BOOL(buf);
		}
		 if (!xdr_vector (xdrs, (char *)objp->identificacionUsuario, MAXIDENTIFICACION2,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->turno))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->noModulo))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->ocupado))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->identificacionUsuario, MAXIDENTIFICACION2,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_notificacion (XDR *xdrs, notificacion *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->modulos, 3,
		sizeof (moduloActualizado), (xdrproc_t) xdr_moduloActualizado))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cantidadUsuariosFilaVirtual))
		 return FALSE;
	return TRUE;
}
