/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "InterfaceClienteServidorModulos.h"
#include "InterfaceServidorModuloServidorDisplay.h"
#include <stdbool.h>
#include <string.h>
#include <stdio.h>




int consultarNUmeroModuloDisponible();
int numeroTurno =1;
int cantidadUsuariosFila = 0;
modulo vectorModulos[3];
usuario filaVirtual[10];

void notificarModulos()
{
	CLIENT *datosConexionServidor;
	void *resultadoEnvio;
	char ipServidor[20];
	strcpy(ipServidor, "localhost");

#ifndef DEBUG 
	//con clnt_create se obtiene la ubicacion al servidor display
	datosConexionServidor == clnt_create(ipServidor, notificar_modulos, notificar_modulos_version, "udp");
	if (datosConexionServidor == NULL)
	{
		clnt_pcreateerror (ipServidor);
		exit (1);
	}
#endif /*DEBUG*/

	notificacion objNotificacion;
	for (int i = 0; i < 3; i++)
	{
		strcpy(objNotificacion.modulos[i].identificacionUsuario,vectorModulos[i].identificacionUsuario);
		objNotificacion.modulos[i].noModulo = vectorModulos[i].noModulo;
		objNotificacion.modulos[i].turno = vectorModulos[i].numeroTurno;
		objNotificacion.modulos[i].ocupado = vectorModulos[i].ocupado;
	}
	objNotificacion.cantidadUsuariosFilaVirtual = cantidadUsuariosFila;

	//Se invoca el procedimiento remoto para enviar la notificacion
	resultadoEnvio = enviarnotificacion_1(&objNotificacion, datosConexionServidor);
	if (resultadoEnvio == (void *) NULL)
	{
		clnt_perror (datosConexionServidor, "call failed");
	}

#ifndef DEBUG
	//Se liberan recursos del lado del cliente
	clnt_destroy (datosConexionServidor);
#endif /*DEBUG*/
}


nodo_turno *  generarturno_1_svc(char **argp, struct svc_req *rqstp)
{
	static nodo_turno  result;
	int posicion = consultarNUmeroModuloDisponible();
	
	printf("\n");

	if(posicion==-1){
		printf("\n Los modulos se encuentran ocupados");
		strcpy(filaVirtual[cantidadUsuariosFila].identificacionUsuario,*argp);
		cantidadUsuariosFila ++; 
		printf("\n El usuario se agrego a la fila virtual.");
	}else{
		printf("\n EL modulo en la poscion %d esta libre y se asignara al usuario con identificacion %s",(posicion+1),*argp);
		vectorModulos[posicion].ocupado = true;
		vectorModulos[posicion].numeroTurno = numeroTurno;
		strcpy(vectorModulos[posicion].identificacionUsuario,*argp);
	}
	result.numeroTurno = numeroTurno;
	result.cantidadUsuariosFilaVirtual = cantidadUsuariosFila;
	strcpy(result.identificacionUsuario,*argp);
	numeroTurno ++;
	
	//Nuevo
	notificarModulos();

	printf("\n"); 
	return &result;
}

int consultarNUmeroModuloDisponible(){
	int posicion = -1;
	for(int i=0; i<3; i++){
		if(vectorModulos[i].ocupado ==false){
			posicion = i;
			break;
		}
	}
	return posicion; 
}
